website: http://marcely.de
version: 1.1.4
name: MBedwars_Kits
author: Marcely1199
main: de.marcely.bedwarsaddon.kits.BedwarsAddonKits
description: This is an add-on for the plugin Marcelys Bedwars
depend: [MBedwars]